#!/bin/sh


viajes=./trips


# bucle por los .json
for file in ${viajes}/*.json
do
  curl -X POST \
    -H "Content-Type: application/json" \
    -d @$file \
    http://localhost:8080/api/mobile/trip


done